apiVersion: v2
name: memobase
description: A user profile-based memory system designed to bring long-term user memory to your Generative AI (GenAI) applications
home: https://github.com/memodb-io/memobase
sources:
  - https://github.com/memodb-io/memobase
  - https://github.com/memodb-io/memobase-helm
type: application
version: 0.0.4
appVersion: 0.0.31
