# Default values for memobase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    pullPolicy: IfNotPresent

core:
  name: memobase
  replicaCount: 1
  image:
    repository: ghcr.io/memodb-io/memobase
    # Tag for memobase  image. Defaults to the chart's appVersion if not specified.
    tag: ""
  accessToken: "token"
  projectId: "memobase"
  config:
    # Storage and Performance
    persistent_chat_blobs: false
    max_chat_blob_buffer_token_size: 1024
    buffer_flush_interval: 3600
    max_profile_subtopics: 15
    max_pre_profile_token_size: 128
    cache_user_profiles_ttl: 1200
    llm_tab_separator: "::"
    
    # Timezone
    use_timezone: ""
    
    # LLM Configuration
    language: "en"
    llm_style: "openai"
    llm_base_url: "https://api.openai.com/v1/"
    llm_api_key: ""
    best_llm_model: "gpt-4o-mini"
    summary_llm_model: ""
    system_prompt: ""
    
    # Embedding Configuration
    enable_event_embedding: true
    embedding_provider: "openai"
    embedding_api_key: ""
    embedding_base_url: ""
    embedding_dim: 1536
    embedding_model: "text-embedding-3-small"
    embedding_max_token_size: 8192
    
    # Profile Configuration
    additional_user_profiles: []
    overwrite_user_profiles: []
    profile_strict_mode: false
    profile_validate_mode: true
    
    # Summary Configuration
    enable_event_summary: true
    minimum_chats_token_size_for_event_summary: 256
    event_tags: []
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

postgresql:
  enabled: true
  username: postgres
  password: postgres
  database: memobase
  port: 5432
  persistence:
    enabled: false
    # if not set, use the default storage class (hostpath in docker kubernetes desktop)
    storageClass: ""
    size: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

redis:
  enabled: true
  password: "memobase"

externalStorage:
  postgresql:
    enabled: false
    # postgresql://username:password@hostname:port/database
    url: ""
    # or use secretName to reference a secret with the url
    secretManger:
      enabled: false
      secretName: "memobase-storage-secrets"
      secretKey: "pg_url"
      csiDriver: "secrets-store.csi.k8s.io"
      secretProviderClass: "memobase-aws-secrets"
  redis:
    enabled: false
    # redis://:{password}@hostname:port/database
    url: ""
    # or use secretName to reference a secret with the url
    secretManger:
      enabled: false
      secretName: "memobase-storage-secrets"
      secretKey: "redis_url"
      csiDriver: "secrets-store.csi.k8s.io"
      secretProviderClass: "memobase-aws-secrets"

serviceAccount:
  create: true
  automount: true
  annotations: {}

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  ingressClassName: ""
  hosts: []
  # - host: chart-example.local

  # TODO: add tls
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


# this is internal, end users don't need to set this
admin:
  enabled: false
  name: memobase-admin
  replicaCount: 1
  accessToken: "token"
  prometheusUrl: ""
  usageTokenLimitActive: "300000"
  usageTokenLimitPro: "300000000"
  image:
    repository: ghcr.io/memodb-io/memobase-admin
    tag: "0.0.7"
    secret:
      # you can get the dockerconfigjson from the command:
      # kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --dry-run=client -o yaml
      dockerconfigjson: ""
  resources:
    requests:
      cpu: 10m
      memory: 12Mi
    limits:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: false
    annotations: {}
    ingressClassName: ""
    hosts: []
    # - host: chart-example.local
      
