apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memobase.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  launch.yaml: |
  
    # Storage and Performance
    {{- if .Values.core.config.persistent_chat_blobs }}
    persistent_chat_blobs: true
    {{- else}}
    persistent_chat_blobs: false
    {{- end }}
    {{- if .Values.core.config.max_chat_blob_buffer_token_size }}
    max_chat_blob_buffer_token_size: {{ .Values.core.config.max_chat_blob_buffer_token_size }}
    {{- end }}
    {{- if .Values.core.config.buffer_flush_interval }}
    buffer_flush_interval: {{ .Values.core.config.buffer_flush_interval }}
    {{- end }}
    {{- if .Values.core.config.max_profile_subtopics }}
    max_profile_subtopics: {{ .Values.core.config.max_profile_subtopics }}
    {{- end }}
    {{- if .Values.core.config.max_pre_profile_token_size }}
    max_pre_profile_token_size: {{ .Values.core.config.max_pre_profile_token_size }}
    {{- end }}
    {{- if .Values.core.config.cache_user_profiles_ttl }}
    cache_user_profiles_ttl: {{ .Values.core.config.cache_user_profiles_ttl | quote }}
    {{- end }}
    {{- if .Values.core.config.llm_tab_separator }}
    llm_tab_separator: {{ .Values.core.config.llm_tab_separator | quote }}
    {{- end }}

    # Timezone
    {{- if .Values.core.config.use_timezone }}
    use_timezone: {{ .Values.core.config.use_timezone | quote }}
    {{- end }}

    # LLM Configuration
    llm_api_key: {{ required "llm_api_key is required" .Values.core.config.llm_api_key | quote }}
    {{- if .Values.core.config.llm_base_url }}
    llm_base_url: {{ .Values.core.config.llm_base_url | quote }}
    {{- end }}
    {{- if .Values.core.config.best_llm_model }}
    best_llm_model: {{ .Values.core.config.best_llm_model | quote }}
    {{- end }}
    {{- if .Values.core.config.language }}
    language: {{ .Values.core.config.language | quote }}
    {{- end }}
    {{- if .Values.core.config.llm_style }}
    llm_style: {{ .Values.core.config.llm_style | quote }}
    {{- end }}
    {{- if .Values.core.config.summary_llm_model }}
    summary_llm_model: {{ .Values.core.config.summary_llm_model | quote }}
    {{- end }}
    {{- if .Values.core.config.system_prompt }}
    system_prompt: {{ .Values.core.config.system_prompt | quote }}
    {{- end }}

    # Embedding Configuration
    {{- if .Values.core.config.enable_event_embedding }}
    enable_event_embedding: true
    {{- else}}
    enable_event_embedding: false
    {{- end }}
    {{- if .Values.core.config.embedding_provider }}
    embedding_provider: {{ .Values.core.config.embedding_provider | quote }}
    {{- end }}
    embedding_api_key: {{ required "embedding_api_key is required" .Values.core.config.embedding_api_key | quote }}
    {{- if .Values.core.config.embedding_base_url }}
    embedding_base_url: {{ .Values.core.config.embedding_base_url | quote }}
    {{- end }}
    {{- if .Values.core.config.embedding_dim }}
    embedding_dim: {{ .Values.core.config.embedding_dim }}
    {{- end }}
    {{- if .Values.core.config.embedding_model }}
    embedding_model: {{ .Values.core.config.embedding_model | quote }}
    {{- end }}
    {{- if .Values.core.config.embedding_max_token_size }}
    embedding_max_token_size: {{ .Values.core.config.embedding_max_token_size }}
    {{- end }}

    # Profile Configuration
    {{- if .Values.core.config.additional_user_profiles }}
    additional_user_profiles:
    {{- range .Values.core.config.additional_user_profiles }}
    - topic: {{ .topic | quote }}
      {{- if .description }}
      description: {{ .description | quote }}
      {{- end }}
      sub_topics:
      {{- range .sub_topics }}
      {{- if kindIs "string" . }}
      - {{ . | quote }}
      {{- else }}
      - name: {{ .name | quote }}
        {{- if .description }}
        description: {{ .description | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.core.config.overwrite_user_profiles }}
    overwrite_user_profiles:
    {{- range .Values.core.config.overwrite_user_profiles }}
    - topic: {{ .topic | quote }}
      {{- if .description }}
      description: {{ .description | quote }}
      {{- end }}
      sub_topics:
      {{- range .sub_topics }}
      {{- if kindIs "string" . }}
      - {{ . | quote }}
      {{- else }}
      - name: {{ .name | quote }}
        {{- if .description }}
        description: {{ .description | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.core.config.profile_strict_mode }}
    profile_strict_mode: true
    {{- else}}
    profile_strict_mode: false
    {{- end }}
    {{- if .Values.core.config.profile_validate_mode }}
    profile_validate_mode: true
    {{- else}}
    profile_validate_mode: false
    {{- end }}
    

    # Summary Configuration
    {{- if .Values.core.config.enable_event_summary }}
    enable_event_summary: true
    {{- else}}
    enable_event_summary: false
    {{- end }}
    {{- if .Values.core.config.minimum_chats_token_size_for_event_summary }}
    minimum_chats_token_size_for_event_summary: {{ .Values.core.config.minimum_chats_token_size_for_event_summary }}
    {{- end }}
    {{- if .Values.core.config.event_tags }}
    event_tags: 
    {{- range .Values.core.config.event_tags }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
