{{- include "memobase.validatePostgresConfig" . }}
{{- include "memobase.validateRedisConfig" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memobase.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "memobase.name" . }}
    {{- include "memobase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.core.hpa.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "memobase.name" . }}
      {{- include "memobase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "memobase.name" . }}
        {{- include "memobase.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "memobase.name" . }}-sa
      containers:
        - name: memobase
          image: {{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              {{- if .Values.postgresql.enabled }}
              value: >-
                postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ include "memobase.name" . }}-db.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}
              {{- else if .Values.externalStorage.postgresql.enabled }}
              {{- if .Values.externalStorage.postgresql.secretManger.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalStorage.postgresql.secretManger.secretName }}
                  key: {{ .Values.externalStorage.postgresql.secretManger.secretKey }}
              {{- else }}
              value: {{ .Values.externalStorage.postgresql.url | quote }}
              {{- end }}
              {{- end }}
            - name: REDIS_URL
              {{- if .Values.redis.enabled }}
              value: >-
                redis://:{{ .Values.redis.password }}@{{ include "memobase.name" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379/0
              {{- else if .Values.externalStorage.redis.enabled }}
              {{- if .Values.externalStorage.redis.secretManger.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalStorage.redis.secretManger.secretName }}
                  key: {{ .Values.externalStorage.redis.secretManger.secretKey }}
              {{- else }}
              value: {{ .Values.externalStorage.redis.url | quote }}
              {{- end }}
              {{- end }}
            - name: ACCESS_TOKEN
              value: {{ .Values.core.accessToken }}
            - name: PROJECT_ID
              value: {{ .Values.core.projectId }}
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          ports:
            - containerPort: 8000
            - containerPort: 9464
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          volumeMounts:
            - name: memobase-config
              mountPath: /app/config.yaml
              subPath: ./app/config.yaml
            {{- if .Values.externalStorage.postgresql.secretManger.enabled }}
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
            {{- end }}
      volumes:
        - name: memobase-config
          configMap:
            name: memobase-config
            items:
              - key: launch.yaml
                path: ./app/config.yaml
        {{- if .Values.externalStorage.postgresql.secretManger.enabled }}
        - name: secrets-store-inline
          csi:
            driver: {{ .Values.externalStorage.postgresql.secretManger.csiDriver | quote }}
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.externalStorage.postgresql.secretManger.secretProviderClass | quote }}
        {{- end }}
