apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "memobase.name" . }}-db
  labels:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "memobase.name" . }}-db
      {{- include "memobase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "memobase.name" . }}-db
        {{- include "memobase.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg17
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.postgresql.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        {{- if .Values.postgresql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: postgres-data
        {{- else }} 
        emptyDir: {}
        {{- end }}
      - name: init-script
        configMap:
          name: {{ include "memobase.name" . }}-db-init
          items:
          - key: init.sql
            path: init.sql
  {{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
        {{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memobase.name" . }}-db-headless
  labels:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memobase.name" . }}-db
  labels:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memobase.name" . }}-db-init
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
