apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memobase.name" . }}-db
  labels:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "memobase.name" . }}-db
      {{- include "memobase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "memobase.name" . }}-db
        {{- include "memobase.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: memobase
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memobase.name" . }}-db
  labels:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ include "memobase.name" . }}-db
    {{- include "memobase.selectorLabels" . | nindent 4 }}
