{{- if .Values.core.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memobase.name" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "memobase.name" . }}
    {{- include "memobase.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    app: {{ include "memobase.name" . }}
    {{- include "memobase.selectorLabels" . | nindent 4 }}
{{- end }}